# =============================================================================
# NYC TAXI ZONE HEATMAP — Interactive Shiny Dashboard
#
# Run from project root (FiveStars_EDA/):
#   shiny::runApp("InteractiveDashboard/dashboard_map.R")
#
# Files needed (relative to project root):
#   Output/dashboard_agg.parquet   — generated by prep_dashboard_data.R
#   Data/NYC_Taxi_Zones.csv        — zone boundary polygons (WKT geometry)
#   Data/taxi_zone_lookup.csv      — zone names and boroughs
# =============================================================================

required_packages <- c("shiny", "leaflet", "sf", "dplyr", "arrow", "scales", "htmltools")
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
}

library(shiny)
library(leaflet)
library(sf)
library(dplyr)
library(arrow)
library(scales)

# =============================================================================
# Load data (once at startup)
# =============================================================================

agg <- read_parquet("Output/dashboard_agg.parquet")

zones_raw <- read.csv("Data/NYC_Taxi_Zones.csv", stringsAsFactors = FALSE)
zones_sf  <- st_as_sf(
  zones_raw,
  wkt = "Shape.Geometry",
  crs = 4326
)
zones_sf <- zones_sf |>
  rename(LocationID = Location.ID) |>
  select(LocationID)

lookup <- read.csv("Data/taxi_zone_lookup.csv", stringsAsFactors = FALSE) |>
  select(LocationID, Zone, Borough, service_zone)

zones_sf <- left_join(zones_sf, lookup, by = "LocationID")

# =============================================================================
# UI
# =============================================================================

ui <- fluidPage(
  tags$head(tags$style(HTML("
    body { margin: 0; font-family: 'Helvetica Neue', Arial, sans-serif; }
    #controls {
      position: absolute; top: 10px; left: 10px; z-index: 1000;
      background: white; padding: 12px 16px; border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.25); min-width: 220px;
    }
    #controls h4 { margin: 0 0 10px 0; font-size: 15px; }
    .kpi-bar {
      position: absolute; bottom: 30px; left: 50%;
      transform: translateX(-50%); z-index: 1000;
      display: flex; gap: 12px;
    }
    .kpi-box {
      background: white; padding: 10px 18px; border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.2); text-align: center;
      min-width: 130px;
    }
    .kpi-label { font-size: 11px; color: #666; margin-bottom: 4px; }
    .kpi-value { font-size: 18px; font-weight: bold; color: #222; }
  "))),

  div(style = "position: relative; height: 100vh;",

    leafletOutput("map", width = "100%", height = "100%"),

    div(id = "controls",
      tags$h4("NYC Taxi Heatmap"),
      radioButtons("zone_type", "Zone type:",
        choices  = c("Pickup zone" = "pickup", "Dropoff zone" = "dropoff"),
        selected = "pickup"
      ),
      radioButtons("metric", "Colour by:",
        choices  = c("Revenue ($)" = "revenue", "Trip count" = "trips"),
        selected = "revenue"
      )
    ),

    div(class = "kpi-bar",
      div(class = "kpi-box",
        div(class = "kpi-label", "Total trips"),
        div(class = "kpi-value", textOutput("kpi_trips", inline = TRUE))
      ),
      div(class = "kpi-box",
        div(class = "kpi-label", "Total revenue"),
        div(class = "kpi-value", textOutput("kpi_revenue", inline = TRUE))
      ),
      div(class = "kpi-box",
        div(class = "kpi-label", "Avg fare"),
        div(class = "kpi-value", textOutput("kpi_fare", inline = TRUE))
      )
    )
  )
)

# =============================================================================
# Server
# =============================================================================

server <- function(input, output, session) {

  map_data <- reactive({
    d <- agg |> filter(.data$zone_type == input$zone_type)
    left_join(zones_sf, d, by = "LocationID")
  })

  output$kpi_trips <- renderText({
    d <- agg |> filter(.data$zone_type == input$zone_type)
    label_comma()(sum(d$trips, na.rm = TRUE))
  })
  output$kpi_revenue <- renderText({
    d <- agg |> filter(.data$zone_type == input$zone_type)
    paste0("$", label_comma()(round(sum(d$revenue, na.rm = TRUE))))
  })
  output$kpi_fare <- renderText({
    d <- agg |> filter(.data$zone_type == input$zone_type)
    paste0("$", round(weighted.mean(d$avg_fare, d$trips, na.rm = TRUE), 2))
  })

  output$map <- renderLeaflet({
    leaflet() |>
      addProviderTiles(providers$CartoDB.Positron) |>
      setView(lng = -73.97, lat = 40.73, zoom = 11)
  })

  observe({
    data <- map_data()
    metric_col <- input$metric

    vals <- data[[metric_col]]

    if (metric_col == "revenue") {
      pal <- colorNumeric(
        palette = "YlOrRd",
        domain  = log1p(vals),
        na.color = "#d0d0d0"
      )
      fill_vals <- log1p(vals)
      legend_title <- "Revenue (log scale)"
    } else {
      pal <- colorNumeric(
        palette  = "YlOrRd",
        domain   = vals,
        na.color = "#d0d0d0"
      )
      fill_vals    <- vals
      legend_title <- "Trip count"
    }

    labels <- sprintf(
      paste0(
        "<strong>%s</strong><br/>%s",
        "<br/>Trips: %s<br/>Revenue: $%s<br/>Avg fare: $%s"
      ),
      data$Zone,
      data$Borough,
      label_comma()(data$trips),
      label_comma()(round(data$revenue)),
      round(data$avg_fare, 2)
    ) |> lapply(htmltools::HTML)

    leafletProxy("map", data = data) |>
      clearShapes() |>
      clearControls() |>
      addPolygons(
        fillColor   = ~pal(fill_vals),
        fillOpacity = 0.75,
        color       = "white",
        weight      = 0.5,
        opacity     = 1,
        label       = labels,
        labelOptions = labelOptions(
          style     = list("font-size" = "13px"),
          direction = "auto"
        ),
        highlightOptions = highlightOptions(
          weight      = 2,
          color       = "#444",
          fillOpacity = 0.9,
          bringToFront = TRUE
        )
      ) |>
      addLegend(
        position = "bottomright",
        pal      = pal,
        values   = fill_vals,
        title    = legend_title,
        opacity  = 0.8
      )
  })
}

shinyApp(ui, server)
